import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";


export const metadata: Metadata = {
  title: "Thought Share | share your thoughts with the world",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-[#0F172A] '>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}